server:
  port: 0

spring:
  application:
    name: licensingservice

  profiles:
    active: default
  config:
    import: configserver:http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  timelimiter:
    configs:
      default:
        cancel-running-future: true
        timeout-duration: 1s
  thread-pool-bulkhead:
    configs:
      default:
        core-thread-pool-size: 30
        max-thread-pool-size: 30
        queue-capacity: 10







